queue_rules:
  - name: default
    conditions: &ChecksQueue
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label=ready-to-merge
    update_method: rebase
    merge_method: fast-forward

pull_request_rules:
  - name: Automatic merge on approval & CI
    conditions:
      - check-success=Ubuntu 22
      - check-success=Ubuntu 24
      - check-success=Windows
      - and: *ChecksQueue
    actions:
      queue:
        name: default
