queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - label!=not-ready

pull_request_rules:
  - name: Automatic merge on approval & CI
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Ubuntu 18
      - check-success=Ubuntu 20
      - check-success=Windows
      - base=main
      - label!=not-ready
    actions:
      queue:
        name: default
        method: fast-forward
        update_method: rebase
