/**********************************************************************************************
 * WARNING: THIS FILE HAS BEEN GENERATED BY REG_MAP_MANAGER TOOLS PLEASE DO NOT MODIFY IT     *
 **********************************************************************************************
 * File: imu_register_map.h                                                                   *
 *                                                                                            *
 * Copyright (c) 2015-2018 Prophesee. All rights reserved.                                    *
 *                                                                                            *
 * Date:           08/10/2018 at 12h05m31s                                                    *
 * Name:           imu_register_map                                                           *
 * Version:        1.0                                                                        *
 * Hash:           5bbb2361abe7cfb517e59136ce8316e506510e8720a3d629adaaa7d948550dfe           *
 **********************************************************************************************
 * WARNING: THIS FILE HAS BEEN GENERATED BY REG_MAP_MANAGER TOOLS PLEASE DO NOT MODIFY IT     *
 *********************************************************************************************/

#ifndef METAVISION_HAL_IMU_REGISTER_MAP_H
#define METAVISION_HAL_IMU_REGISTER_MAP_H

//------------------------------------------------------------------------------------------------------------
// IMU
//------------------------------------------------------------------------------------------------------------

#define IMU_BASE_ADDR 0x00000000
#define IMU_LAST_ADDR 0x00000075
#define IMU_SIZE 0x00000080

#define IMU_AX_MSB_ADDR 0x0000003B // IMU Accelerometer X-Axis MSB: AX[15:8]
#define IMU_AX_MSB_VALUE_BIT_IDX 0 // IMU Accelerometer X-Axis MSB: AX[15:8] value
#define IMU_AX_MSB_VALUE_WIDTH 8
#define IMU_AX_MSB_VALUE_DEFAULT 0x00000000

#define IMU_AX_LSB_ADDR 0x0000003C // IMU Accelerometer X-Axis LSB: AX[7:0]
#define IMU_AX_LSB_VALUE_BIT_IDX 0 // IMU Accelerometer X-Axis LSB: AX[7:0] value
#define IMU_AX_LSB_VALUE_WIDTH 8
#define IMU_AX_LSB_VALUE_DEFAULT 0x00000000

#define IMU_AY_MSB_ADDR 0x0000003D // IMU Accelerometer Y-Axis MSB: AY[15:8]
#define IMU_AY_MSB_VALUE_BIT_IDX 0 // IMU Accelerometer Y-Axis MSB: AY[15:8] value
#define IMU_AY_MSB_VALUE_WIDTH 8
#define IMU_AY_MSB_VALUE_DEFAULT 0x00000000

#define IMU_AY_LSB_ADDR 0x0000003E // IMU Accelerometer Y-Axis LSB: AY[7:0]
#define IMU_AY_LSB_VALUE_BIT_IDX 0 // IMU Accelerometer Y-Axis LSB: AY[7:0] value
#define IMU_AY_LSB_VALUE_WIDTH 8
#define IMU_AY_LSB_VALUE_DEFAULT 0x00000000

#define IMU_AZ_MSB_ADDR 0x0000003F // IMU Accelerometer Z-Axis MSB: AZ[15:8]
#define IMU_AZ_MSB_VALUE_BIT_IDX 0 // IMU Accelerometer Z-Axis MSB: AZ[15:8] value
#define IMU_AZ_MSB_VALUE_WIDTH 8
#define IMU_AZ_MSB_VALUE_DEFAULT 0x00000000

#define IMU_AZ_LSB_ADDR 0x00000040 // IMU Accelerometer Z-Axis LSB: AZ[7:0]
#define IMU_AZ_LSB_VALUE_BIT_IDX 0 // IMU Accelerometer Z-Axis LSB: AZ[7:0] value
#define IMU_AZ_LSB_VALUE_WIDTH 8
#define IMU_AZ_LSB_VALUE_DEFAULT 0x00000000

#define IMU_GX_MSB_ADDR 0x00000043 // IMU Gyroscope X-Axis MSB: GX[15:8]
#define IMU_GX_MSB_VALUE_BIT_IDX 0 // IMU Gyroscope X-Axis MSB: GX[15:8] value
#define IMU_GX_MSB_VALUE_WIDTH 8
#define IMU_GX_MSB_VALUE_DEFAULT 0x00000000

#define IMU_GX_LSB_ADDR 0x00000044 // IMU Gyroscope X-Axis LSB: GX[7:0]
#define IMU_GX_LSB_VALUE_BIT_IDX 0 // IMU Gyroscope X-Axis LSB: GX[7:0] value
#define IMU_GX_LSB_VALUE_WIDTH 8
#define IMU_GX_LSB_VALUE_DEFAULT 0x00000000

#define IMU_GY_MSB_ADDR 0x00000045 // IMU Gyroscope Y-Axis MSB: GY[15:8]
#define IMU_GY_MSB_VALUE_BIT_IDX 0 // IMU Gyroscope Y-Axis MSB: GY[15:8] value
#define IMU_GY_MSB_VALUE_WIDTH 8
#define IMU_GY_MSB_VALUE_DEFAULT 0x00000000

#define IMU_GY_LSB_ADDR 0x00000046 // IMU Gyroscope Y-Axis LSB: GY[7:0]
#define IMU_GY_LSB_VALUE_BIT_IDX 0 // IMU Gyroscope Y-Axis LSB: GY[7:0] value
#define IMU_GY_LSB_VALUE_WIDTH 8
#define IMU_GY_LSB_VALUE_DEFAULT 0x00000000

#define IMU_GZ_MSB_ADDR 0x00000047 // IMU Gyroscope Z-Axis MSB: GZ[15:8]
#define IMU_GZ_MSB_VALUE_BIT_IDX 0 // IMU Gyroscope Z-Axis MSB: GZ[15:8] value
#define IMU_GZ_MSB_VALUE_WIDTH 8
#define IMU_GZ_MSB_VALUE_DEFAULT 0x00000000

#define IMU_GZ_LSB_ADDR 0x00000048 // IMU Gyroscope Z-Axis LSB: GZ[7:0]
#define IMU_GZ_LSB_VALUE_BIT_IDX 0 // IMU Gyroscope Z-Axis LSB: GZ[7:0] value
#define IMU_GZ_LSB_VALUE_WIDTH 8
#define IMU_GZ_LSB_VALUE_DEFAULT 0x00000000

#define IMU_WHOAMI_ADDR 0x00000075 // IMU Who Am I
#define IMU_WHOAMI_VALUE_BIT_IDX 0 // IMU Who Am I value
#define IMU_WHOAMI_VALUE_WIDTH 8
#define IMU_WHOAMI_VALUE_DEFAULT 0x00000000

#endif // METAVISION_HAL_IMU_REGISTER_MAP_H
