/**********************************************************************************************
 * WARNING: THIS FILE HAS BEEN GENERATED BY REG_MAP_MANAGER TOOLS PLEASE DO NOT MODIFY IT     *
 **********************************************************************************************
 * File: system_config_register_map.h                                                         *
 *                                                                                            *
 * Copyright (c) 2015-2018 Prophesee. All rights reserved.                                    *
 *                                                                                            *
 * Date:           08/10/2018 at 12h05m31s                                                    *
 * Name:           system_config_register_map                                                 *
 * Version:        1.0                                                                        *
 * Hash:           ddf36b6aa5dbf427ce800525d4200684d94698274aa678a7101ecb0f5a886070           *
 **********************************************************************************************
 * WARNING: THIS FILE HAS BEEN GENERATED BY REG_MAP_MANAGER TOOLS PLEASE DO NOT MODIFY IT     *
 *********************************************************************************************/

#ifndef METAVISION_HAL_SYSTEM_CONFIG_REGISTER_MAP_H
#define METAVISION_HAL_SYSTEM_CONFIG_REGISTER_MAP_H

//------------------------------------------------------------------------------------------------------------
// SYSTEM_CONFIG
//------------------------------------------------------------------------------------------------------------

#define SYSTEM_CONFIG_BASE_ADDR 0x00000000
#define SYSTEM_CONFIG_LAST_ADDR 0x0000000C
#define SYSTEM_CONFIG_SIZE 0x00000010

#define SYSTEM_CONFIG_ID_ADDR 0x00000000
#define SYSTEM_CONFIG_ID_BIT_IDX 0
#define SYSTEM_CONFIG_ID_WIDTH 8
#define SYSTEM_CONFIG_ID_DEFAULT 0x00000015

#define SYSTEM_CONFIG_VERSION_ADDR 0x00000004
#define SYSTEM_CONFIG_VERSION_MICRO_BIT_IDX 0
#define SYSTEM_CONFIG_VERSION_MICRO_WIDTH 8
#define SYSTEM_CONFIG_VERSION_MICRO_DEFAULT 0x00000000
#define SYSTEM_CONFIG_VERSION_MINOR_BIT_IDX 8
#define SYSTEM_CONFIG_VERSION_MINOR_WIDTH 8
#define SYSTEM_CONFIG_VERSION_MINOR_DEFAULT 0x00000000
#define SYSTEM_CONFIG_VERSION_MAJOR_BIT_IDX 16
#define SYSTEM_CONFIG_VERSION_MAJOR_WIDTH 8
#define SYSTEM_CONFIG_VERSION_MAJOR_DEFAULT 0x00000000

#define SYSTEM_CONFIG_BUILD_DATE_ADDR 0x00000008
#define SYSTEM_CONFIG_BUILD_DATE_BIT_IDX 0
#define SYSTEM_CONFIG_BUILD_DATE_WIDTH 32
#define SYSTEM_CONFIG_BUILD_DATE_DEFAULT 0x00000000

#define SYSTEM_CONFIG_VERSION_CONTROL_ID_ADDR 0x0000000C
#define SYSTEM_CONFIG_VERSION_CONTROL_ID_BIT_IDX 0
#define SYSTEM_CONFIG_VERSION_CONTROL_ID_WIDTH 32
#define SYSTEM_CONFIG_VERSION_CONTROL_ID_DEFAULT 0x00000000

#endif // METAVISION_HAL_SYSTEM_CONFIG_REGISTER_MAP_H
