name: Upload Windows Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 1 */2 *"

env:
  win_binaries_download_address: "https://prophesee-bamboo.s3.eu-west-1.amazonaws.com/build-env/vcpkg-export-20230323-MV4.0.0.zip"
  ffmpeg_archive_download_address: "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z"

jobs:
  get_artifacts:
    name: Get VCPKG Export Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Downloading binaries
        timeout-minutes: 10
        run: |
          curl -L -o vcpkg-export.zip $win_binaries_download_address
          curl -L -o ffmpeg-archive.7z $ffmpeg_archive_download_address

      - name: Uploading binaries to storage
        uses: actions/upload-artifact@master
        with:
          name: vcpkg_binaries
          path: vcpkg-export.zip

      - name: Uploading ffmpeg to storage
        uses: actions/upload-artifact@master
        with:
          name: ffmpeg_archive
          path: ffmpeg-archive.7z
